### ISSUE TITLE
flet build windows error . 

### ISSUE THREAD

**Issue by bobwatcherx** [ndonkoHenri/flet-github-action-workflows#1]
hi i try you code for windows build script yml 

how to fix . i set flet in requirements.txt file

![Screenshot 2024-08-19 133803](https://github.com/user-attachments/assets/6af92179-3685-49b5-a59a-7c24b585b9c6)

**Comment by ndonkoHenri** [comment]
I made a video: https://youtu.be/ObO-D2TD_wo

**Comment by joesandiroz2** [comment]
now i still error like this

UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 11: character maps to <undefined>
           Flutter 3.27.3           Flutter 3.27.3

from this workfile . how to fix

`name: Windows Build
 
on:
  # Runs on push to any of the below branches
  push:
    branches:
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master
      - main
 
  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:
 
env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.2
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
 
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
 
    - name: Flet Build Windows
      run: |
        flutter config --no-analytics
        flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION
 
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: error
        overwrite: false
`

**Comment by joesandiroz2** [comment]
flet version 0.26 . i latest upgrade

**Comment by ndonkoHenri** [comment]
I updated the builds. See my windows action [here](https://github.com/ndonkoHenri/flet-github-action-workflows/actions/runs/13710337976/job/38345318977) made from this [example](https://github.com/ndonkoHenri/flet-github-action-workflows/tree/example).

Feel free to provide feedback.
