### ISSUE TITLE
customize the app

### ISSUE THREAD

**Issue by Wabski9** [ndonkoHenri/flet-github-action-workflows#10]
Hi again,

I try to customize the file to build an apk, I want to know how to add custom icon, etc...
 where should I added it.

thanks

**Comment by Wabski9** [comment]
also how to set the permissions for android

**Comment by ndonkoHenri** [comment]
See the Flet documentation:
- icons: https://flet.dev/docs/publish#icons
- permissions: https://flet.dev/docs/publish#permissions

**Comment by Wabski9** [comment]
dear, 
I see that doc, but what is the modifications I should made in apk-build.yml.

I added the icon.png on the project dir but it not added to the app, so how I modify the .yml?

**Comment by ndonkoHenri** [comment]
Can you share a link to your project repository?

**Comment by Wabski9** [comment]
I have privet project, dear maybe you don't understand my point 
here the code you provided for build android,
name: APK Build

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin' # See https://github.com/marketplace/actions/setup-java-jdk#supported-distributions for available options
        java-version: '21'

    - name: Flet Build APK
      run: |
        flutter config --no-analytics # disable flutter analytics
        flet build apk --verbose    # adapt the command to your needs - https://flet.dev/docs/publish 

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: apk-build-artifact  # the name of the artifact
        path: build/apk  # location of Flet build output
        if-no-files-found: error  # Fail the action with an error message if no files are found
        overwrite: false  # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.,

can you show me where should I modify on this file to add custom icon for the android app?
also the permissions ?

**Comment by ndonkoHenri** [comment]
The icon is not specified in your actions file. You need to add the icon in assets directory as mentioned in the docs.

I can't really help any further if I don't see your project and file organization.
