### ISSUE TITLE
Events problems

### ISSUE THREAD

**Issue by elverlin** [ndonkoHenri/flet-github-action-workflows#3]
When I export my app as an APK file, the events don't trigger. For example, I have a button that, when clicked, makes a request using the 'requests' module and displays the request information. This issue persists despite all my attempts, even though it works perfectly in my code editor.

**Comment by ndonkoHenri** [comment]
Can I see your requirements file or have a link to your repo?

Does this happen even with simple buttons or just with those making requests.

**Comment by elverlin** [comment]
https://github.com/elverlin/Test

If i put time, re, or os in requierements.txt it generate an error when exporting
