### ISSUE TITLE
problem using the builder for windows

### ISSUE THREAD

**Issue by Razielthc** [ndonkoHenri/flet-github-action-workflows#4]
[6_Flet Build Windows.txt](https://github.com/user-attachments/files/17110979/6_Flet.Build.Windows.txt)
I send the log file the problem seems to be the decoding of some of the files

**Comment by ndonkoHenri** [comment]
Thanks for reporting. I came up with a fix in https://github.com/flet-dev/flet/pull/4108.
Please sub to it for further updates concerning this issue.
