### ISSUE TITLE
Flet project with multiple files

### ISSUE THREAD

**Issue by Om-decoder** [ndonkoHenri/flet-github-action-workflows#9]
You make Really amazing tools to convert the fley to apk, my inquiries about how I can used it if I have multiple files like main.py to login and redirect, database.py, user page, admin page!

What should be changed in branches? Or it's enough to add the main only!

**Comment by Om-decoder** [comment]
Because I try long time with buildozer and flutter flet build apk, and it show errors and each time I fixed the errors it show other error, really I'm tired and the last way is to try this

**Comment by ndonkoHenri** [comment]
If your Flet app runs normally on your computer, then simply upload it to your github repository and follow this tutorial I made: https://youtu.be/ObO-D2TD_wo

Let me know if you have further questions.
